[tools]
direnv = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
lazydocker = "latest"
luajit = "latest"
neovim = "latest"
node = "latest"
ripgrep = "latest"
rust = "latest"
shfmt = "latest"
starship = "latest"
tinytex = "latest"
tree-sitter = "latest"
usage = "latest"
yazi = "latest"
zig = "latest"
lazygit = "latest"
lazyssh = "latest"

